language:
  elixir

addons:
  postgresql: "9.6"

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.5.2
    - otp_release: 20.0
      elixir: 1.6.2
    - otp_release: 21.0
      elixir: 1.7.3

script:
  - mix ecto.create
  - mix ecto.migrate
  - mix espec --trace
